### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by mki-c2c**
configparser required

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
As far as I know, configparser is part of the Python standard library.
https://docs.python.org/3/library/configparser.html

**Comment by mki-c2c** [comment]
strange, I had a problem, I'll check what happened

**Comment by mki-c2c** [comment]
alright, I dropped into a python2 virtualenv without being aware of it.
yes, the package is included in python3
However keeping the dependency won't hurt, or otherwise you could explicitly exclude python2 from running the app (to have a better error message)

**Comment by arnaud-morvan** [comment]
I could change the README file, but "make install" already create a Python3 venv : https://github.com/camptocamp/qgis_plugins.xml/blob/master/Makefile#L2

**Comment by mki-c2c** [comment]
I see, I skipped th makefile and directly pip installed the tool. I think it's nice if  the python package can be pip installed without depending on a makefile, but of course the tool works fine as it is.

I think the PR can be closed.

**Pull request closed without merging**
