### PR TITLE
Move to Python3 and support execution in a plugin source directory

### PR DESCRIPTION
**Pull request by arnaud-morvan**
And add url option as now we push on a S3 bucket, we cannot run it on server.

### CODE REVIEW

**Review by sbrunner — APPROVED** [review]
By the way, where is this used?

**Comment by arnaud-morvan** [comment]
@sbrunner : old qgis.camptocamp.net server has been shut down, now we've got an AWS S3 bucket now : https://qgis.camptocamp.net/plugins/dpfe_qgis3/1.3/plugins.xml

I use this to create the plugin.xml locally, before pushing xml and zip on AWS.
For the moment it result in a different repository for each plugin, but this fit with my needs for the moment.

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by sbrunner** [comment]
By the way, I move it to Camptocamp :-)

**Pull request merged**
